[package]
name = "reinla"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
forger = "0.1.1"
peroxide = { version = "0.34.1", features = ["parquet"] }
